### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type object 

### ISSUE THREAD

**Issue by kalpak44** [octokit/webhooks.js#123]
I have this code

```
const SmeeClient = require('smee-client')

process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0;

const smee = new SmeeClient({
  source: 'https://smee.io/ou0EqBOIPJ1QuwDQ',
  target: 'https://localhost:453/webhook/documentsigning',
  logger: console
})

const events = smee.start()
```

When I have a request from docusign to 'https://smee.io/ou0EqBOIPJ1QuwDQ' this throws and app stop. Error message is attached: 

```
_http_outgoing.js:690
      throw new ERR_INVALID_ARG_TYPE('chunk', ['string', 'Buffer'], chunk);
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type object
    at ClientRequest.end (_http_outgoing.js:690:13)
    at Request._end (C:\Users\User\Desktop\proxy\node_modules\superagent\lib\node\index.js:1021:9)
    at Request.end (C:\Users\User\Desktop\proxy\node_modules\superagent\lib\node\index.js:777:15)
    at Client.onmessage (C:\Users\User\Desktop\proxy\node_modules\smee-client\index.js:35:9)
    at EventSource.emit (events.js:189:13)
    at _emit (C:\Users\User\Desktop\proxy\node_modules\eventsource\lib\eventsource.js:242:17)
    at parseEventStreamLine (C:\Users\User\Desktop\proxy\node_modules\eventsource\lib\eventsource.js:257:9)
    at IncomingMessage.<anonymous> (C:\Users\User\Desktop\proxy\node_modules\eventsource\lib\eventsource.js:217:11)
    at IncomingMessage.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
```

**Comment by gr2m** [comment]
This seems to be a problem with https://github.com/probot/smee-client, not with `@octokit/webhooks`? Would you mind filing the issue there instead?

**Comment by lokucrazy** [comment]
@gr2m @kalpak44 hi was this issue resolved?  I couldn't find a related issue on the smee-client repo and a co-worked is coming across the same issue.
