### ISSUE TITLE
[DOCS]: Smee setup documentation has an error

### ISSUE THREAD

**Issue by monsonjeremy** [octokit/webhooks.js#899]
### Describe the need

The following code snippet is given in the Smee setup section for local development of webhooks:

```javascript
const webhookProxyUrl = "https://smee.io/IrqK0nopGAOc847"; // replace with your own Webhook Proxy URL
const source = new EventSource(webhookProxyUrl);
source.onmessage = (event) => {
  const webhookEvent = JSON.parse(event.data);
  webhooks
    .verifyAndReceive({
      id: webhookEvent["x-request-id"],
      name: webhookEvent["x-github-event"],
      signature: webhookEvent["x-hub-signature"],
      payload: webhookEvent.body,
    })
    .catch(console.error);
};
```

When running this on Node 18 I'm getting the following error:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
```

The issue here stems from the argument passed to `verifyAndReceive`. The function expects the payload to be `type string or an instance of Buffer, TypedArray, or DataView` but here we are passing an Object since we have called `JSON.parse` on `event.data`

Updating the code to use `JSON.stringify(webhookEvent.body)` fixes the issue for me.

```javascript
const webhookProxyUrl = "https://smee.io/IrqK0nopGAOc847"; // replace with your own Webhook Proxy URL
const source = new EventSource(webhookProxyUrl);
source.onmessage = (event) => {
  const webhookEvent = JSON.parse(event.data);
  webhooks
    .verifyAndReceive({
      id: webhookEvent["x-request-id"],
      name: webhookEvent["x-github-event"],
      signature: webhookEvent["x-hub-signature"],
      payload: JSON.stringify(webhookEvent.body),
    })
    .catch(console.error);
};
```

### SDK Version

Octokit NPM 3.1.0

### Relevant log output

```shell
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at new NodeError (node:internal/errors:399:5)
    at Hmac.update (node:internal/crypto/hash:109:11)
    at sign (/REDACTED/node_modules/@octokit/webhooks-methods/dist-node/index.js:58:75)
    at verify (/REDACTED/node_modules/@octokit/webhooks-methods/dist-node/index.js:81:11)
    at verifyAndReceive (/REDACTED/node_modules/@octokit/webhooks/dist-node/index.js:471:69)
    at EventSource.source.onmessage (/REDACTED/src/Routes/Github.routes.ts:50:10)
    at EventSource.emit (node:events:513:28)
    at EventSource.emit (node:domain:489:12)
    at _emit (/REDACTED/node_modules/eventsource/lib/eventsource.js:287:17)
    at parseEventStreamLine (/REDACTED/node_modules/eventsource/lib/eventsource.js:302:9)
    at IncomingMessage.<anonymous> (/REDACTED/node_modules/eventsource/lib/eventsource.js:259:11)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at HTTPParser.parserOnBody (node:_http_common:131:24)
    at TLSSocket.socketOnData (node:_http_client:542:22)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
Thank you for bringing this issue up! Feel free to submit a Pull Request submitting a fix to the documentation
